name: entao_jsonrpc
description: JSON RPC 2.0 for dart language.
version: 1.0.5
repository: https://github.com/yangentao/entao_jsonrpc
homepage: https://github.com/yangentao/entao_jsonrpc

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  #  entao_dutil: ^2.3.4
  entao_log: ^2.0.1
  entao_lint: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
